services:
  api:
    image: ghrc.io/jin-ramen/pjhong-api:latest
    restart: unless-stopped

  web:
    build: ghcr.io/jin-ramen/pjhong-web:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data

volumes:
  caddy_data: